// Bundles the Java debug adapter into one file the desktop app ships as a
// Tauri resource (apps/desktop/src-tauri/resources/java-dap.cjs).
//   node packages/java-dap/build.mjs [--check] [--out <file>]
import { build } from "esbuild";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outArg = process.argv.indexOf("--out");
const check = process.argv.includes("--check");
const outfile = outArg > 0 ? resolve(process.argv[outArg + 1]) : resolve(here, "../../apps/desktop/src-tauri/resources/java-dap.cjs");

const result = await build({
  entryPoints: [resolve(here, "src/main.ts")],
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node18",
  outfile: check ? undefined : outfile,
  write: !check,
  legalComments: "none",
  banner: { js: "// TMCode Java debug adapter (generated by packages/java-dap/build.mjs; do not edit)." },
  logLevel: "warning",
});

if (check) {
  // CI: fail when the committed bundle is stale.
  const fresh = new TextDecoder().decode(result.outputFiles[0].contents);
  const committed = readFileSync(outfile, "utf8");
  if (fresh !== committed) {
    console.error("apps/desktop/src-tauri/resources/java-dap.cjs is stale: run `node packages/java-dap/build.mjs`.");
    process.exit(1);
  }
}
