fn main() {
    // Every app command needs an explicit permission, granted to the workbench
    // webview only (capabilities/workbench.json). Preview webviews get none.
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "app_info",
            "take_pending_open",
            "set_native_theme",
            "ws_open",
            "ws_reopen",
            "ws_open_file",
            "ws_open_path",
            "ws_reveal",
            "ws_read_dir",
            "ws_read_file",
            "ws_write_file",
            "ws_create_file",
            "ws_create_dir",
            "ws_rename",
            "ws_remove",
            "pty_spawn",
            "pty_write",
            "pty_resize",
            "pty_kill",
            "toolchains_detect",
            "run_start",
            "run_input",
            "run_kill",
            "preview_publish",
            "exam_device",
            "exam_workspace",
            "journal_load",
            "journal_append",
            "journal_mark_synced",
            "update_check",
            "update_install",
            "ext_fetch",
            "ext_list",
            "ext_install",
            "ext_uninstall",
            "ext_read_file",
        ]),
    ))
    .expect("failed to run tauri-build");
}
