// Bundles the Node.js extension host into one file the desktop app ships as a
// Tauri resource (apps/desktop/src-tauri/resources/exthost.cjs).
//   node packages/exthost/build.mjs [--check]
import { build } from "esbuild";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outfile = resolve(here, "../../apps/desktop/src-tauri/resources/exthost.cjs");

const result = await build({
  entryPoints: [resolve(here, "src/node/main.ts")],
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node18",
  outfile: process.argv.includes("--check") ? undefined : outfile,
  write: !process.argv.includes("--check"),
  legalComments: "none",
  banner: { js: "// TMCode extension host (generated by packages/exthost/build.mjs; do not edit)." },
  logLevel: "warning",
});

if (process.argv.includes("--check")) {
  // CI: fail when the committed bundle is stale.
  const fresh = new TextDecoder().decode(result.outputFiles[0].contents);
  const committed = readFileSync(outfile, "utf8");
  if (fresh !== committed) {
    console.error("apps/desktop/src-tauri/resources/exthost.cjs is stale: run `node packages/exthost/build.mjs`.");
    process.exit(1);
  }
}
