import { gitignore, json, launch, readme, type Template } from "./kit";

const TODOS_NOTE = ["", "Try it: Run › Open API Tester, pick a route on the left and Send."];

/** Backend & APIs: Run Project starts the server; the API Tester calls it. */
export const BACKEND: Template[] = [
  {
    id: "node-express",
    label: "Node.js API (Express)",
    description: "A REST API (to-dos) with a debug configuration",
    icon: "server",
    language: "javascript",
    category: "Backend & APIs",
    tools: ["node", "npm"],
    setup: { command: "npm install", note: "Installs Express" },
    files: {
      "package.json": json({ name: "node-api", private: true, type: "module", main: "src/index.js", scripts: { dev: "node --watch src/index.js", start: "node src/index.js" }, dependencies: { express: "^5.0.0" } }),
      "src/index.js": `import express from "express";\n\nconst app = express();\napp.use(express.json());\n\nconst todos = [{ id: 1, title: "Learn Express", done: false }];\n\napp.get("/api/todos", (req, res) => res.json(todos));\n\napp.get("/api/todos/:id", (req, res) => {\n  const todo = todos.find((t) => t.id === Number(req.params.id));\n  if (!todo) return res.status(404).json({ error: "Not found" });\n  res.json(todo);\n});\n\napp.post("/api/todos", (req, res) => {\n  if (!req.body?.title) return res.status(400).json({ error: "title is required" });\n  const todo = { id: todos.length + 1, title: req.body.title, done: false };\n  todos.push(todo);\n  res.status(201).json(todo);\n});\n\napp.delete("/api/todos/:id", (req, res) => {\n  const i = todos.findIndex((t) => t.id === Number(req.params.id));\n  if (i < 0) return res.status(404).json({ error: "Not found" });\n  todos.splice(i, 1);\n  res.status(204).end();\n});\n\nconst port = process.env.PORT ?? 3000;\napp.listen(port, () => console.log(\`Server running on http://localhost:\${port}\`));\n`,
      ".vscode/launch.json": launch([{ type: "node", request: "launch", name: "Debug server", program: "${workspaceFolder}/src/index.js" }]),
      ".gitignore": gitignore([".env"]),
      "README.md": readme("Node.js API (Express)", ["Run Project starts the server (it restarts when you save). F5 debugs it with breakpoints.", ...TODOS_NOTE]),
    },
  },
  {
    id: "node-typescript",
    label: "Node.js (TypeScript)",
    description: "TypeScript run directly with tsx, watch mode and debugging",
    icon: "symbol-namespace",
    language: "typescript",
    category: "Backend & APIs",
    tools: ["node", "npm"],
    setup: { command: "npm install", note: "Installs TypeScript and tsx" },
    files: {
      "package.json": json({ name: "node-ts", private: true, type: "module", scripts: { dev: "tsx watch src/index.ts", start: "tsx src/index.ts", build: "tsc", test: "node --test" }, devDependencies: { tsx: "^4.19.0", typescript: "^5.6.0", "@types/node": "^22.0.0" } }),
      "tsconfig.json": json({ compilerOptions: { target: "ES2022", module: "NodeNext", moduleResolution: "NodeNext", strict: true, outDir: "dist", skipLibCheck: true }, include: ["src"] }),
      "src/index.ts": `interface Student {\n  name: string;\n  marks: number[];\n}\n\nfunction average(values: number[]): number {\n  return values.reduce((a, b) => a + b, 0) / values.length;\n}\n\nconst students: Student[] = [\n  { name: "Ada", marks: [90, 84, 77] },\n  { name: "Ben", marks: [65, 72, 80] },\n];\n\nfor (const s of students) {\n  console.log(\`\${s.name}: \${average(s.marks).toFixed(1)}\`);\n}\n`,
      ".gitignore": gitignore(),
      "README.md": readme("Node.js with TypeScript", ["Run Project runs `tsx watch`, re-running on every save. F5 on `src/index.ts` debugs it."]),
    },
  },
  {
    id: "nestjs",
    label: "NestJS API",
    description: "Controllers, services and modules, with watch mode",
    icon: "server",
    language: "typescript",
    category: "Backend & APIs",
    tools: ["node", "npm"],
    setup: { command: "npm install", note: "Installs NestJS" },
    files: {
      "package.json": json({
        name: "nest-api",
        private: true,
        scripts: { "start:dev": "nest start --watch", start: "nest start", build: "nest build" },
        dependencies: { "@nestjs/common": "^11.0.0", "@nestjs/core": "^11.0.0", "@nestjs/platform-express": "^11.0.0", "reflect-metadata": "^0.2.0", rxjs: "^7.8.0" },
        devDependencies: { "@nestjs/cli": "^11.0.0", typescript: "^5.6.0", "@types/node": "^22.0.0", "@types/express": "^5.0.0" },
      }),
      "nest-cli.json": json({ $schema: "https://json.schemastore.org/nest-cli", collection: "@nestjs/schematics", sourceRoot: "src" }),
      "tsconfig.json": json({ compilerOptions: { module: "commonjs", target: "ES2022", declaration: false, emitDecoratorMetadata: true, experimentalDecorators: true, outDir: "./dist", baseUrl: "./", strict: true, strictPropertyInitialization: false, skipLibCheck: true }, include: ["src"] }),
      "src/main.ts": `import { NestFactory } from "@nestjs/core";\nimport { AppModule } from "./app.module";\n\nasync function bootstrap() {\n  const app = await NestFactory.create(AppModule);\n  await app.listen(process.env.PORT ?? 3000);\n  console.log(\`Server running on \${await app.getUrl()}\`);\n}\nbootstrap();\n`,
      "src/app.module.ts": `import { Module } from "@nestjs/common";\nimport { TodosController } from "./todos.controller";\nimport { TodosService } from "./todos.service";\n\n@Module({ controllers: [TodosController], providers: [TodosService] })\nexport class AppModule {}\n`,
      "src/todos.service.ts": `import { Injectable, NotFoundException } from "@nestjs/common";\n\nexport interface Todo {\n  id: number;\n  title: string;\n  done: boolean;\n}\n\n@Injectable()\nexport class TodosService {\n  private todos: Todo[] = [{ id: 1, title: "Learn NestJS", done: false }];\n\n  all() {\n    return this.todos;\n  }\n\n  one(id: number) {\n    const t = this.todos.find((x) => x.id === id);\n    if (!t) throw new NotFoundException("No such todo");\n    return t;\n  }\n\n  create(title: string) {\n    const t = { id: this.todos.length + 1, title, done: false };\n    this.todos.push(t);\n    return t;\n  }\n}\n`,
      "src/todos.controller.ts": `import { Body, Controller, Get, Param, ParseIntPipe, Post } from "@nestjs/common";\nimport { TodosService } from "./todos.service";\n\n@Controller("api/todos")\nexport class TodosController {\n  constructor(private readonly todos: TodosService) {}\n\n  @Get()\n  all() {\n    return this.todos.all();\n  }\n\n  @Get(":id")\n  one(@Param("id", ParseIntPipe) id: number) {\n    return this.todos.one(id);\n  }\n\n  @Post()\n  create(@Body() body: { title: string }) {\n    return this.todos.create(body.title);\n  }\n}\n`,
      ".gitignore": gitignore(),
      "README.md": readme("NestJS API", ["Run Project starts `nest start --watch` (port 3000).", ...TODOS_NOTE]),
    },
  },
  {
    id: "flask",
    label: "Python API (Flask)",
    description: "Flask routes with JSON and a debug configuration",
    icon: "server",
    language: "python",
    category: "Backend & APIs",
    tools: ["python"],
    setup: { command: "python -m pip install -r requirements.txt", note: "Installs Flask" },
    files: {
      "requirements.txt": "flask>=3.0\n",
      "app.py": `from flask import Flask, jsonify, request\n\napp = Flask(__name__)\ntodos = [{"id": 1, "title": "Learn Flask", "done": False}]\n\n\n@app.get("/api/todos")\ndef all_todos():\n    return jsonify(todos)\n\n\n@app.get("/api/todos/<int:todo_id>")\ndef one_todo(todo_id):\n    todo = next((t for t in todos if t["id"] == todo_id), None)\n    return (jsonify(todo), 200) if todo else (jsonify(error="Not found"), 404)\n\n\n@app.post("/api/todos")\ndef create_todo():\n    data = request.get_json(silent=True) or {}\n    if not data.get("title"):\n        return jsonify(error="title is required"), 400\n    todo = {"id": len(todos) + 1, "title": data["title"], "done": False}\n    todos.append(todo)\n    return jsonify(todo), 201\n\n\n@app.route("/")\ndef home():\n    return "<h1>Flask is running</h1><p>Try <a href='/api/todos'>/api/todos</a></p>"\n\n\nif __name__ == "__main__":\n    app.run(debug=True)\n`,
      ".vscode/launch.json": launch([{ type: "debugpy", request: "launch", name: "Flask", module: "flask", args: ["--app", "app", "run"], jinja: true }]),
      ".gitignore": gitignore([".env"]),
      "README.md": readme("Flask API", ["Run Project starts `flask run --debug` (port 5000). F5 debugs it.", ...TODOS_NOTE]),
    },
  },
  {
    id: "fastapi",
    label: "Python API (FastAPI)",
    description: "Typed endpoints with automatic docs at /docs",
    icon: "server",
    language: "python",
    category: "Backend & APIs",
    tools: ["python"],
    setup: { command: "python -m pip install -r requirements.txt", note: "Installs FastAPI and Uvicorn" },
    files: {
      "requirements.txt": "fastapi>=0.115\nuvicorn[standard]>=0.30\n",
      "main.py": `from fastapi import FastAPI, HTTPException\nfrom pydantic import BaseModel\n\napp = FastAPI(title="To-do API")\n\n\nclass TodoIn(BaseModel):\n    title: str\n\n\nclass Todo(TodoIn):\n    id: int\n    done: bool = False\n\n\ntodos: list[Todo] = [Todo(id=1, title="Learn FastAPI")]\n\n\n@app.get("/api/todos")\ndef all_todos() -> list[Todo]:\n    return todos\n\n\n@app.get("/api/todos/{todo_id}")\ndef one_todo(todo_id: int) -> Todo:\n    for t in todos:\n        if t.id == todo_id:\n            return t\n    raise HTTPException(status_code=404, detail="Not found")\n\n\n@app.post("/api/todos", status_code=201)\ndef create_todo(body: TodoIn) -> Todo:\n    todo = Todo(id=len(todos) + 1, title=body.title)\n    todos.append(todo)\n    return todo\n`,
      ".vscode/launch.json": launch([{ type: "debugpy", request: "launch", name: "FastAPI", module: "uvicorn", args: ["main:app", "--reload"] }]),
      ".gitignore": gitignore(),
      "README.md": readme("FastAPI", ["Run Project starts Uvicorn (port 8000). Interactive docs: http://localhost:8000/docs", ...TODOS_NOTE]),
    },
  },
  {
    id: "django",
    label: "Python Web (Django)",
    description: "A Django site with a view, a JSON endpoint and SQLite",
    icon: "server",
    language: "python",
    category: "Backend & APIs",
    tools: ["python"],
    setup: { command: "python -m pip install -r requirements.txt && python manage.py migrate", note: "Installs Django and creates the database" },
    files: {
      "requirements.txt": "django>=5.0\n",
      "manage.py": `#!/usr/bin/env python\nimport os\nimport sys\n\nif __name__ == "__main__":\n    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "site_app.settings")\n    from django.core.management import execute_from_command_line\n\n    execute_from_command_line(sys.argv)\n`,
      "site_app/__init__.py": "",
      "site_app/settings.py": `from pathlib import Path\n\nBASE_DIR = Path(__file__).resolve().parent.parent\nSECRET_KEY = "dev-only-change-me"\nDEBUG = True\nALLOWED_HOSTS = ["localhost", "127.0.0.1"]\n\nINSTALLED_APPS = [\n    "django.contrib.admin",\n    "django.contrib.auth",\n    "django.contrib.contenttypes",\n    "django.contrib.sessions",\n    "django.contrib.messages",\n    "django.contrib.staticfiles",\n]\n\nMIDDLEWARE = [\n    "django.middleware.security.SecurityMiddleware",\n    "django.contrib.sessions.middleware.SessionMiddleware",\n    "django.middleware.common.CommonMiddleware",\n    "django.middleware.csrf.CsrfViewMiddleware",\n    "django.contrib.auth.middleware.AuthenticationMiddleware",\n    "django.contrib.messages.middleware.MessageMiddleware",\n]\n\nROOT_URLCONF = "site_app.urls"\nTEMPLATES = [\n    {\n        "BACKEND": "django.template.backends.django.DjangoTemplates",\n        "DIRS": [],\n        "APP_DIRS": True,\n        "OPTIONS": {"context_processors": ["django.template.context_processors.request", "django.contrib.auth.context_processors.auth", "django.contrib.messages.context_processors.messages"]},\n    }\n]\nWSGI_APPLICATION = "site_app.wsgi.application"\nDATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": BASE_DIR / "db.sqlite3"}}\nSTATIC_URL = "static/"\nDEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"\n`,
      "site_app/urls.py": `from django.contrib import admin\nfrom django.urls import path\n\nfrom . import views\n\nurlpatterns = [\n    path("", views.home),\n    path("api/hello/", views.hello),\n    path("admin/", admin.site.urls),\n]\n`,
      "site_app/views.py": `from django.http import HttpResponse, JsonResponse\n\n\ndef home(request):\n    return HttpResponse("<h1>Django is running</h1><p>Try <a href='/api/hello/'>/api/hello/</a></p>")\n\n\ndef hello(request):\n    name = request.GET.get("name", "world")\n    return JsonResponse({"message": f"Hello, {name}!"})\n`,
      "site_app/wsgi.py": `import os\n\nfrom django.core.wsgi import get_wsgi_application\n\nos.environ.setdefault("DJANGO_SETTINGS_MODULE", "site_app.settings")\napplication = get_wsgi_application()\n`,
      ".gitignore": gitignore(["db.sqlite3"]),
      "README.md": readme("Django site", ["Run Project starts `manage.py runserver` (port 8000). Run Task… also has migrate, test and shell.", "", "Create an admin user in the terminal: `python manage.py createsuperuser`."]),
    },
  },
  {
    id: "spring-boot",
    label: "Java API (Spring Boot)",
    description: "Spring Boot 3 REST controller with Maven",
    icon: "coffee",
    language: "java",
    category: "Backend & APIs",
    tools: ["java", "mvn"],
    files: {
      "pom.xml": `<?xml version="1.0" encoding="UTF-8"?>\n<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">\n  <modelVersion>4.0.0</modelVersion>\n  <parent>\n    <groupId>org.springframework.boot</groupId>\n    <artifactId>spring-boot-starter-parent</artifactId>\n    <version>3.3.5</version>\n    <relativePath/>\n  </parent>\n  <groupId>rw.ac.nga</groupId>\n  <artifactId>demo</artifactId>\n  <version>1.0.0</version>\n  <properties>\n    <java.version>17</java.version>\n  </properties>\n  <dependencies>\n    <dependency>\n      <groupId>org.springframework.boot</groupId>\n      <artifactId>spring-boot-starter-web</artifactId>\n    </dependency>\n    <dependency>\n      <groupId>org.springframework.boot</groupId>\n      <artifactId>spring-boot-starter-test</artifactId>\n      <scope>test</scope>\n    </dependency>\n  </dependencies>\n  <build>\n    <plugins>\n      <plugin>\n        <groupId>org.springframework.boot</groupId>\n        <artifactId>spring-boot-maven-plugin</artifactId>\n      </plugin>\n    </plugins>\n  </build>\n</project>\n`,
      "src/main/java/rw/ac/nga/demo/DemoApplication.java": `package rw.ac.nga.demo;\n\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n\n@SpringBootApplication\npublic class DemoApplication {\n    public static void main(String[] args) {\n        SpringApplication.run(DemoApplication.class, args);\n    }\n}\n`,
      "src/main/java/rw/ac/nga/demo/TodoController.java": `package rw.ac.nga.demo;\n\nimport java.util.ArrayList;\nimport java.util.List;\nimport org.springframework.http.HttpStatus;\nimport org.springframework.http.ResponseEntity;\nimport org.springframework.web.bind.annotation.*;\n\n@RestController\n@RequestMapping("/api/todos")\npublic class TodoController {\n    public record Todo(int id, String title, boolean done) {}\n\n    private final List<Todo> todos = new ArrayList<>(List.of(new Todo(1, "Learn Spring Boot", false)));\n\n    @GetMapping\n    public List<Todo> all() {\n        return todos;\n    }\n\n    @GetMapping("/{id}")\n    public ResponseEntity<Todo> one(@PathVariable int id) {\n        return todos.stream().filter(t -> t.id() == id).findFirst().map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build());\n    }\n\n    @PostMapping\n    @ResponseStatus(HttpStatus.CREATED)\n    public Todo create(@RequestBody Todo body) {\n        Todo t = new Todo(todos.size() + 1, body.title(), false);\n        todos.add(t);\n        return t;\n    }\n}\n`,
      "src/main/resources/application.properties": "server.port=8080\nspring.application.name=demo\n",
      "src/test/java/rw/ac/nga/demo/DemoApplicationTests.java": `package rw.ac.nga.demo;\n\nimport org.junit.jupiter.api.Test;\nimport org.springframework.boot.test.context.SpringBootTest;\n\n@SpringBootTest\nclass DemoApplicationTests {\n    @Test\n    void contextLoads() {}\n}\n`,
      ".gitignore": gitignore([".mvn/", "*.class"]),
      "README.md": readme("Spring Boot API", ["Run Project runs `mvn spring-boot:run` (port 8080). Run Task… › `maven: test` runs the tests.", ...TODOS_NOTE]),
    },
  },
  {
    id: "php",
    label: "PHP Website",
    description: "PHP pages and a JSON endpoint on PHP's built-in server",
    icon: "server",
    language: "php",
    category: "Backend & APIs",
    tools: ["php"],
    files: {
      "index.php": `<?php\n$name = htmlspecialchars($_GET['name'] ?? 'world');\n?>\n<!doctype html>\n<html lang="en">\n<head>\n  <meta charset="utf-8">\n  <title>PHP site</title>\n  <style>body { font-family: system-ui; max-width: 36rem; margin: 3rem auto; }</style>\n</head>\n<body>\n  <h1>Hello, <?= $name ?>!</h1>\n  <form>\n    <input name="name" placeholder="Your name">\n    <button>Greet</button>\n  </form>\n  <p>Today is <?= date('l, j F Y') ?>. The JSON endpoint is <a href="api.php">api.php</a>.</p>\n</body>\n</html>\n`,
      "api.php": `<?php\nheader('Content-Type: application/json');\n$todos = [['id' => 1, 'title' => 'Learn PHP', 'done' => false]];\nif ($_SERVER['REQUEST_METHOD'] === 'POST') {\n    $body = json_decode(file_get_contents('php://input'), true) ?? [];\n    if (empty($body['title'])) {\n        http_response_code(400);\n        echo json_encode(['error' => 'title is required']);\n        exit;\n    }\n    http_response_code(201);\n    echo json_encode(['id' => 2, 'title' => $body['title'], 'done' => false]);\n    exit;\n}\necho json_encode($todos);\n`,
      "README.md": readme("PHP website", ["Run Project starts `php -S localhost:8000` and opens the built-in browser.", "", "Run a single PHP file with ▶ (it runs `php file.php` in a terminal)."]),
    },
  },
  {
    id: "laravel",
    label: "Laravel (PHP)",
    description: "Creates a Laravel app with Composer, then artisan serve",
    icon: "server",
    language: "php",
    category: "Backend & APIs",
    tools: ["php", "composer"],
    setup: { command: "composer create-project laravel/laravel app", note: "Downloads Laravel into app/ (a few minutes)" },
    files: {
      "README.md": readme("Laravel", ["The setup creates the app in `app/`. Then Run Project starts `php artisan serve` (port 8000).", "", "Run Task… has artisan migrate, test, route:list and tinker."]),
    },
  },
  {
    id: "sinatra",
    label: "Ruby API (Sinatra)",
    description: "A small Ruby web app with JSON routes",
    icon: "ruby",
    language: "ruby",
    category: "Backend & APIs",
    tools: ["ruby", "bundle"],
    setup: { command: "bundle install", note: "Installs Sinatra" },
    files: {
      Gemfile: `source "https://rubygems.org"\n\ngem "sinatra", "~> 4.0"\ngem "rackup"\ngem "puma"\n`,
      "app.rb": `require "sinatra"\nrequire "json"\n\nset :port, 4567\nTODOS = [{ id: 1, title: "Learn Sinatra", done: false }]\n\nget "/" do\n  "<h1>Sinatra is running</h1><p>Try <a href='/api/todos'>/api/todos</a></p>"\nend\n\nget "/api/todos" do\n  content_type :json\n  TODOS.to_json\nend\n\npost "/api/todos" do\n  content_type :json\n  body = JSON.parse(request.body.read) rescue {}\n  halt 400, { error: "title is required" }.to_json unless body["title"]\n  todo = { id: TODOS.size + 1, title: body["title"], done: false }\n  TODOS << todo\n  status 201\n  todo.to_json\nend\n`,
      "README.md": readme("Sinatra", ["Run Project starts `bundle exec ruby app.rb` (port 4567).", ...TODOS_NOTE]),
    },
  },
  {
    id: "rails",
    label: "Ruby on Rails",
    description: "Creates a Rails app (rails new), then rails server",
    icon: "ruby",
    language: "ruby",
    category: "Backend & APIs",
    tools: ["ruby", "rails"],
    setup: { command: "rails new app --skip-git", note: "Creates a Rails app in app/ (a few minutes)" },
    files: {
      "README.md": readme("Ruby on Rails", ["The setup creates the app in `app/`. Then Run Project starts `bin/rails server` (port 3000).", "", "Generate code in the terminal: `bin/rails generate scaffold Post title:string body:text`."]),
    },
  },
  {
    id: "go-api",
    label: "Go API (net/http)",
    description: "Go's standard library HTTP server with routing",
    icon: "server",
    language: "go",
    category: "Backend & APIs",
    tools: ["go"],
    files: {
      "go.mod": "module example.com/api\n\ngo 1.22\n",
      "main.go": `package main\n\nimport (\n\t"encoding/json"\n\t"log"\n\t"net/http"\n\t"strconv"\n\t"sync"\n)\n\ntype Todo struct {\n\tID    int    \`json:"id"\`\n\tTitle string \`json:"title"\`\n\tDone  bool   \`json:"done"\`\n}\n\nvar (\n\tmu    sync.Mutex\n\ttodos = []Todo{{ID: 1, Title: "Learn Go", Done: false}}\n)\n\nfunc writeJSON(w http.ResponseWriter, status int, v any) {\n\tw.Header().Set("Content-Type", "application/json")\n\tw.WriteHeader(status)\n\tjson.NewEncoder(w).Encode(v)\n}\n\nfunc main() {\n\thttp.HandleFunc("GET /api/todos", func(w http.ResponseWriter, r *http.Request) {\n\t\tmu.Lock()\n\t\tdefer mu.Unlock()\n\t\twriteJSON(w, 200, todos)\n\t})\n\thttp.HandleFunc("GET /api/todos/{id}", func(w http.ResponseWriter, r *http.Request) {\n\t\tid, _ := strconv.Atoi(r.PathValue("id"))\n\t\tmu.Lock()\n\t\tdefer mu.Unlock()\n\t\tfor _, t := range todos {\n\t\t\tif t.ID == id {\n\t\t\t\twriteJSON(w, 200, t)\n\t\t\t\treturn\n\t\t\t}\n\t\t}\n\t\twriteJSON(w, 404, map[string]string{"error": "Not found"})\n\t})\n\thttp.HandleFunc("POST /api/todos", func(w http.ResponseWriter, r *http.Request) {\n\t\tvar body Todo\n\t\tif err := json.NewDecoder(r.Body).Decode(&body); err != nil || body.Title == "" {\n\t\t\twriteJSON(w, 400, map[string]string{"error": "title is required"})\n\t\t\treturn\n\t\t}\n\t\tmu.Lock()\n\t\tdefer mu.Unlock()\n\t\tbody.ID = len(todos) + 1\n\t\ttodos = append(todos, body)\n\t\twriteJSON(w, 201, body)\n\t})\n\tlog.Println("Server running on http://localhost:8080")\n\tlog.Fatal(http.ListenAndServe(":8080", nil))\n}\n`,
      "README.md": readme("Go API", ["Run Project starts `go run .` (port 8080). F5 debugs it with Delve when installed.", ...TODOS_NOTE]),
    },
  },
  {
    id: "aspnet",
    label: "C# API (ASP.NET Core)",
    description: "A minimal API with dotnet watch",
    icon: "server",
    language: "csharp",
    category: "Backend & APIs",
    tools: ["dotnet"],
    files: {
      "Api.csproj": `<Project Sdk="Microsoft.NET.Sdk.Web">\n  <PropertyGroup>\n    <TargetFramework>net8.0</TargetFramework>\n    <Nullable>enable</Nullable>\n    <ImplicitUsings>enable</ImplicitUsings>\n  </PropertyGroup>\n</Project>\n`,
      "Program.cs": `var builder = WebApplication.CreateBuilder(args);\nvar app = builder.Build();\n\nvar todos = new List<Todo> { new(1, "Learn ASP.NET Core", false) };\n\napp.MapGet("/api/todos", () => todos);\napp.MapGet("/api/todos/{id:int}", (int id) => todos.FirstOrDefault(t => t.Id == id) is { } t ? Results.Ok(t) : Results.NotFound());\napp.MapPost("/api/todos", (TodoIn body) =>\n{\n    var t = new Todo(todos.Count + 1, body.Title, false);\n    todos.Add(t);\n    return Results.Created($"/api/todos/{t.Id}", t);\n});\n\napp.Run("http://localhost:5000");\n\nrecord Todo(int Id, string Title, bool Done);\nrecord TodoIn(string Title);\n`,
      ".gitignore": gitignore(["bin/", "obj/"]),
      "README.md": readme("ASP.NET Core minimal API", ["Run Project starts `dotnet watch run` (port 5000).", ...TODOS_NOTE]),
    },
  },
];
