import { gitignore, ioTests, launch, readme, type Template } from "./kit";

/** Mobile & desktop apps. */
export const MOBILE: Template[] = [
  {
    id: "flutter",
    label: "Flutter App",
    description: "A Flutter app for web, desktop and phones (hot reload)",
    icon: "device-mobile",
    language: "dart",
    category: "Mobile & desktop",
    tools: ["flutter"],
    setup: { command: "flutter create . --platforms=web,android,ios,macos,windows,linux && flutter pub get", note: "Adds the platform folders and downloads packages" },
    files: {
      "pubspec.yaml": `name: flutter_app\ndescription: A Flutter app made in TMCode.\npublish_to: none\nversion: 1.0.0+1\n\nenvironment:\n  sdk: ">=3.4.0 <4.0.0"\n\ndependencies:\n  flutter:\n    sdk: flutter\n\ndev_dependencies:\n  flutter_test:\n    sdk: flutter\n\nflutter:\n  uses-material-design: true\n`,
      "lib/main.dart": `import 'package:flutter/material.dart';\n\nvoid main() => runApp(const MyApp());\n\nclass MyApp extends StatelessWidget {\n  const MyApp({super.key});\n\n  @override\n  Widget build(BuildContext context) {\n    return MaterialApp(\n      title: 'Flutter App',\n      theme: ThemeData(colorSchemeSeed: Colors.indigo, useMaterial3: true),\n      home: const CounterPage(),\n    );\n  }\n}\n\nclass CounterPage extends StatefulWidget {\n  const CounterPage({super.key});\n\n  @override\n  State<CounterPage> createState() => _CounterPageState();\n}\n\nclass _CounterPageState extends State<CounterPage> {\n  int _count = 0;\n\n  @override\n  Widget build(BuildContext context) {\n    return Scaffold(\n      appBar: AppBar(title: const Text('Hello, Flutter')),\n      body: Center(\n        child: Text('Pressed $_count times', style: Theme.of(context).textTheme.headlineMedium),\n      ),\n      floatingActionButton: FloatingActionButton(\n        onPressed: () => setState(() => _count++),\n        child: const Icon(Icons.add),\n      ),\n    );\n  }\n}\n`,
      "test/widget_test.dart": `import 'package:flutter_test/flutter_test.dart';\nimport 'package:flutter_app/main.dart';\n\nvoid main() {\n  testWidgets('the counter goes up', (tester) async {\n    await tester.pumpWidget(const MyApp());\n    expect(find.text('Pressed 0 times'), findsOneWidget);\n    await tester.tap(find.byType(FloatingActionButton));\n    await tester.pump();\n    expect(find.text('Pressed 1 times'), findsOneWidget);\n  });\n}\n`,
      ".vscode/launch.json": launch([{ type: "dart", request: "launch", name: "Flutter", program: "lib/main.dart" }]),
      ".gitignore": gitignore([".dart_tool/", ".flutter-plugins*", "build/"]),
      "README.md": readme("Flutter app", ["Run Project serves the web version in the built-in browser (press **r** in its terminal for hot reload).", "", "Run Task… › `flutter: run on this computer` opens the desktop app; `flutter: test` runs the widget test. F5 debugs with the Flutter debugger."]),
    },
  },
  {
    id: "dart",
    label: "Dart Console App",
    description: "A Dart program with a test",
    icon: "symbol-method",
    language: "dart",
    category: "Mobile & desktop",
    tools: ["dart"],
    setup: { command: "dart pub get", note: "Downloads the test package" },
    files: {
      "pubspec.yaml": `name: dart_app\nenvironment:\n  sdk: ">=3.4.0 <4.0.0"\ndev_dependencies:\n  test: ^1.25.0\n`,
      "bin/main.dart": `import 'package:dart_app/greeting.dart';\n\nvoid main(List<String> args) {\n  print(greet(args.isEmpty ? 'Dart' : args.first));\n}\n`,
      "lib/greeting.dart": `String greet(String name) => 'Hello, $name!';\n`,
      "test/greeting_test.dart": `import 'package:dart_app/greeting.dart';\nimport 'package:test/test.dart';\n\nvoid main() {\n  test('greets by name', () => expect(greet('Ada'), 'Hello, Ada!'));\n}\n`,
      ".gitignore": gitignore([".dart_tool/"]),
      "README.md": readme("Dart console app", ["Run Project runs `dart run`; Run Task… › `dart: test` runs the tests."]),
    },
  },
  {
    id: "java-swing",
    label: "Java Desktop App (Swing)",
    description: "A window with a button and a text field, no build tool",
    icon: "coffee",
    language: "java",
    category: "Mobile & desktop",
    tools: ["java"],
    files: {
      "Main.java": `import javax.swing.*;\nimport java.awt.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        SwingUtilities.invokeLater(() -> {\n            JFrame frame = new JFrame("Greeter");\n            JTextField name = new JTextField(16);\n            JLabel out = new JLabel("Type your name and press Greet");\n            JButton greet = new JButton("Greet");\n            greet.addActionListener(e -> out.setText("Hello, " + name.getText() + "!"));\n\n            JPanel panel = new JPanel(new FlowLayout());\n            panel.add(name);\n            panel.add(greet);\n            frame.add(panel, BorderLayout.NORTH);\n            frame.add(out, BorderLayout.CENTER);\n            frame.setSize(420, 140);\n            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);\n            frame.setVisible(true);\n        });\n    }\n}\n`,
      "README.md": readme("Java Swing app", ["▶ on `Main.java` compiles and runs it; the window opens on your desktop."]),
    },
  },
  {
    id: "swift",
    label: "Swift Package",
    description: "A Swift command-line program with a test",
    icon: "symbol-method",
    language: "swift",
    category: "Mobile & desktop",
    tools: ["swift"],
    files: {
      "Package.swift": `// swift-tools-version:5.9\nimport PackageDescription\n\nlet package = Package(\n    name: "App",\n    targets: [\n        .executableTarget(name: "App"),\n        .testTarget(name: "AppTests", dependencies: ["App"]),\n    ]\n)\n`,
      "Sources/App/main.swift": `func greet(_ name: String) -> String { "Hello, \\(name)!" }\n\nprint(greet("Swift"))\n`,
      "Tests/AppTests/AppTests.swift": `import XCTest\n\nfinal class AppTests: XCTestCase {\n    func testTruth() { XCTAssertEqual(1 + 1, 2) }\n}\n`,
      ".gitignore": gitignore([".build/", ".swiftpm/"]),
      "README.md": readme("Swift package", ["Run Project runs `swift run`; Run Task… › `swift: test` runs the tests."]),
    },
  },
];

/** General-purpose languages, each with a runnable program (▶ / F5). */
export const LANGUAGES: Template[] = [
  {
    id: "python",
    label: "Python",
    description: "A Python program with a test and a debug configuration",
    icon: "symbol-method",
    language: "python",
    category: "Languages",
    tools: ["python"],
    files: {
      "main.py": `def greet(name: str) -> str:\n    return f"Hello, {name}!"\n\n\nif __name__ == "__main__":\n    name = input("What is your name? ")\n    print(greet(name))\n`,
      "test_main.py": `from main import greet\n\n\ndef test_greet():\n    assert greet("Ada") == "Hello, Ada!"\n`,
      ".tmcode/tests.json": ioTests("main.py", [["greets Ada", "Ada\n", "What is your name? Hello, Ada!\n"]]),
      ".vscode/launch.json": launch([{ type: "debugpy", request: "launch", name: "Python: main.py", program: "${workspaceFolder}/main.py", console: "integratedTerminal" }]),
      ".gitignore": gitignore([".pytest_cache/"]),
      "README.md": readme("Python project", ["F5 debugs `main.py` (breakpoints, variables, stepping). The Testing view (beaker) runs `.tmcode/tests.json`."]),
    },
  },
  {
    id: "c",
    label: "C Programming",
    description: "A C program with a Makefile, input tests and debugging",
    icon: "symbol-class",
    language: "c",
    category: "Languages",
    tools: ["cc"],
    files: {
      "main.c": `#include <stdio.h>\n\n/* Reads numbers until the end of input and prints their sum and average. */\nint main(void) {\n    double x, sum = 0;\n    int n = 0;\n    while (scanf("%lf", &x) == 1) {\n        sum += x;\n        n++;\n    }\n    if (n == 0) {\n        printf("No numbers\\n");\n        return 0;\n    }\n    printf("Count: %d\\nSum: %.2f\\nAverage: %.2f\\n", n, sum, sum / n);\n    return 0;\n}\n`,
      Makefile: `CFLAGS = -std=c17 -Wall -Wextra -g\n\napp: main.c\n\t$(CC) $(CFLAGS) -o app main.c\n\nrun: app\n\t./app\n\nclean:\n\trm -f app\n`,
      ".tmcode/tests.json": ioTests("main.c", [["three numbers", "4 8 6\n", "Count: 3\nSum: 18.00\nAverage: 6.00\n"], ["no numbers", "", "No numbers\n"]]),
      ".gitignore": gitignore(["app", "*.o", "*.dSYM/"]),
      "README.md": readme("C program", ["▶ (Ctrl+F5) compiles and runs `main.c`: type numbers, then Ctrl+D (Ctrl+Z on Windows).", "", "F5 debugs it (breakpoints, variables). The Testing view (beaker) checks the input/output tests in `.tmcode/tests.json`."]),
    },
  },
  {
    id: "c-structures",
    label: "C: Data Structures (multi-file)",
    description: "A linked list and a stack across .h/.c files with a Makefile",
    icon: "symbol-structure",
    language: "c",
    category: "Languages",
    tools: ["cc", "make"],
    files: {
      "list.h": `#ifndef LIST_H\n#define LIST_H\n\ntypedef struct Node {\n    int value;\n    struct Node *next;\n} Node;\n\nNode *list_push(Node *head, int value);\nvoid list_print(const Node *head);\nint list_length(const Node *head);\nvoid list_free(Node *head);\n\n#endif\n`,
      "list.c": `#include <stdio.h>\n#include <stdlib.h>\n#include "list.h"\n\nNode *list_push(Node *head, int value) {\n    Node *n = malloc(sizeof *n);\n    n->value = value;\n    n->next = head;\n    return n;\n}\n\nvoid list_print(const Node *head) {\n    for (const Node *p = head; p; p = p->next) printf("%d%s", p->value, p->next ? " -> " : "\\n");\n}\n\nint list_length(const Node *head) {\n    int n = 0;\n    for (; head; head = head->next) n++;\n    return n;\n}\n\nvoid list_free(Node *head) {\n    while (head) {\n        Node *next = head->next;\n        free(head);\n        head = next;\n    }\n}\n`,
      "main.c": `#include <stdio.h>\n#include "list.h"\n\nint main(void) {\n    Node *list = NULL;\n    for (int i = 1; i <= 5; i++) list = list_push(list, i * i);\n    list_print(list);\n    printf("Length: %d\\n", list_length(list));\n    list_free(list);\n    return 0;\n}\n`,
      Makefile: `CFLAGS = -std=c17 -Wall -Wextra -g\nOBJ = main.o list.o\n\napp: $(OBJ)\n\t$(CC) $(CFLAGS) -o app $(OBJ)\n\n%.o: %.c list.h\n\t$(CC) $(CFLAGS) -c $<\n\nrun: app\n\t./app\n\nclean:\n\trm -f app $(OBJ)\n`,
      ".gitignore": gitignore(["app", "*.o"]),
      "README.md": readme("C data structures", ["Run Project runs `make run`. Run Task… › `make: clean` removes the build.", "", "Debug: Run Task… › `make: app`, then F5 with the launch.json `C: app` configuration (Add Configuration… › C/C++)."]),
    },
  },
  {
    id: "cpp",
    label: "C++",
    description: "A C++17 program with input tests and debugging",
    icon: "symbol-class",
    language: "cpp",
    category: "Languages",
    tools: ["cxx"],
    files: {
      "main.cpp": `#include <iostream>\n#include <string>\n\nint main() {\n    std::string name;\n    std::cout << "What is your name? ";\n    std::getline(std::cin, name);\n    std::cout << "Hello, " << name << "!" << std::endl;\n    return 0;\n}\n`,
      ".tmcode/tests.json": ioTests("main.cpp", [["greets Ada", "Ada\n", "What is your name? Hello, Ada!\n"]]),
      ".gitignore": gitignore(["main", "*.o"]),
      "README.md": readme("C++ program", ["▶ compiles and runs `main.cpp`; F5 debugs it. The Testing view runs `.tmcode/tests.json`."]),
    },
  },
  {
    id: "cpp-cmake",
    label: "C++ (CMake)",
    description: "main.cpp with a CMake build and a Makefile task",
    icon: "symbol-class",
    language: "cpp",
    category: "Languages",
    tools: ["cxx", "cmake"],
    files: {
      "main.cpp": `#include <iostream>\n#include <vector>\n#include <numeric>\n\nint main() {\n    std::vector<int> v{3, 1, 4, 1, 5, 9, 2, 6};\n    std::cout << "Sum: " << std::accumulate(v.begin(), v.end(), 0) << std::endl;\n    return 0;\n}\n`,
      "CMakeLists.txt": `cmake_minimum_required(VERSION 3.16)\nproject(app CXX)\nset(CMAKE_CXX_STANDARD 17)\nadd_executable(app main.cpp)\n`,
      ".gitignore": gitignore(["build/"]),
      "README.md": readme("C++ (CMake)", ["Run Project configures and builds with CMake, then runs `app`. F5 on `main.cpp` debugs it."]),
    },
  },
  {
    id: "java-maven",
    label: "Java (Maven)",
    description: "A Maven project with a Main class and a JUnit test",
    icon: "coffee",
    language: "java",
    category: "Languages",
    tools: ["java", "mvn"],
    files: {
      "pom.xml": `<?xml version="1.0" encoding="UTF-8"?>\n<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">\n  <modelVersion>4.0.0</modelVersion>\n  <groupId>rw.ac.nga</groupId>\n  <artifactId>app</artifactId>\n  <version>1.0.0</version>\n  <properties>\n    <maven.compiler.release>17</maven.compiler.release>\n    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>\n  </properties>\n  <dependencies>\n    <dependency>\n      <groupId>org.junit.jupiter</groupId>\n      <artifactId>junit-jupiter</artifactId>\n      <version>5.11.0</version>\n      <scope>test</scope>\n    </dependency>\n  </dependencies>\n</project>\n`,
      "src/main/java/Main.java": `public class Main {\n    static int square(int x) {\n        return x * x;\n    }\n\n    public static void main(String[] args) {\n        System.out.println("Hello from Java! 7 squared is " + square(7));\n    }\n}\n`,
      "src/test/java/MainTest.java": `import static org.junit.jupiter.api.Assertions.assertEquals;\n\nimport org.junit.jupiter.api.Test;\n\nclass MainTest {\n    @Test\n    void squares() {\n        assertEquals(49, Main.square(7));\n    }\n}\n`,
      ".gitignore": gitignore(),
      "README.md": readme("Java (Maven)", ["▶ on `Main.java` runs it. Run Task… › `maven: test` runs JUnit; `maven: package` builds the jar."]),
    },
  },
  {
    id: "java",
    label: "Java (single file)",
    description: "Main.java with keyboard input and tests, no build tool",
    icon: "coffee",
    language: "java",
    category: "Languages",
    tools: ["java"],
    files: {
      "Main.java": `import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner in = new Scanner(System.in);\n        System.out.print("What is your name? ");\n        String name = in.nextLine();\n        System.out.println("Hello, " + name + "!");\n    }\n}\n`,
      ".tmcode/tests.json": ioTests("Main.java", [["greets Ada", "Ada\n", "What is your name? Hello, Ada!\n"]]),
      "README.md": readme("Java", ["▶ compiles and runs `Main.java`. The Testing view checks `.tmcode/tests.json`."]),
    },
  },
  {
    id: "kotlin",
    label: "Kotlin",
    description: "A Kotlin program compiled with kotlinc",
    icon: "symbol-method",
    language: "kotlin",
    category: "Languages",
    tools: ["kotlinc", "java"],
    files: {
      "Main.kt": `data class Student(val name: String, val marks: List<Int>) {\n    val average get() = marks.average()\n}\n\nfun main() {\n    val students = listOf(Student("Ada", listOf(90, 84, 77)), Student("Ben", listOf(65, 72, 80)))\n    students.sortedByDescending { it.average }.forEach {\n        println("\${it.name}: \${"%.1f".format(it.average)}")\n    }\n}\n`,
      ".gitignore": gitignore(["*.jar"]),
      "README.md": readme("Kotlin", ["▶ on `Main.kt` compiles it with `kotlinc` and runs the jar in a terminal."]),
    },
  },
  {
    id: "csharp",
    label: "C# Console (.NET)",
    description: "A .NET console app",
    icon: "symbol-class",
    language: "csharp",
    category: "Languages",
    tools: ["dotnet"],
    files: {
      "App.csproj": `<Project Sdk="Microsoft.NET.Sdk">\n  <PropertyGroup>\n    <OutputType>Exe</OutputType>\n    <TargetFramework>net8.0</TargetFramework>\n    <Nullable>enable</Nullable>\n    <ImplicitUsings>enable</ImplicitUsings>\n  </PropertyGroup>\n</Project>\n`,
      "Program.cs": `Console.Write("What is your name? ");\nvar name = Console.ReadLine();\nConsole.WriteLine($"Hello, {name}!");\n`,
      ".gitignore": gitignore(["bin/", "obj/"]),
      "README.md": readme("C# console", ["Run Project runs `dotnet run`. Run Task… has build and test."]),
    },
  },
  {
    id: "go",
    label: "Go",
    description: "A Go module with a test",
    icon: "symbol-method",
    language: "go",
    category: "Languages",
    tools: ["go"],
    files: {
      "go.mod": "module example.com/hello\n\ngo 1.22\n",
      "main.go": `package main\n\nimport "fmt"\n\nfunc Greet(name string) string {\n\treturn "Hello, " + name + "!"\n}\n\nfunc main() {\n\tfmt.Println(Greet("Go"))\n}\n`,
      "main_test.go": `package main\n\nimport "testing"\n\nfunc TestGreet(t *testing.T) {\n\tif got := Greet("Ada"); got != "Hello, Ada!" {\n\t\tt.Fatalf("got %q", got)\n\t}\n}\n`,
      "README.md": readme("Go", ["Run Project runs `go run .`; Run Task… › `go: test` runs the tests. F5 debugs with Delve when installed."]),
    },
  },
  {
    id: "rust",
    label: "Rust",
    description: "A Cargo project with a unit test",
    icon: "symbol-method",
    language: "rust",
    category: "Languages",
    tools: ["cargo"],
    files: {
      "Cargo.toml": `[package]\nname = "hello"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\n`,
      "src/main.rs": `fn greet(name: &str) -> String {\n    format!("Hello, {name}!")\n}\n\nfn main() {\n    println!("{}", greet("Rust"));\n}\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n\n    #[test]\n    fn greets() {\n        assert_eq!(greet("Ada"), "Hello, Ada!");\n    }\n}\n`,
      ".gitignore": gitignore(["target/"]),
      "README.md": readme("Rust", ["Run Project runs `cargo run`; Run Task… › `cargo: test` runs the tests. F5 debugs with LLDB."]),
    },
  },
  {
    id: "ruby",
    label: "Ruby",
    description: "A Ruby script with classes and blocks",
    icon: "ruby",
    language: "ruby",
    category: "Languages",
    tools: ["ruby"],
    files: {
      "main.rb": `class Student\n  attr_reader :name, :marks\n\n  def initialize(name, marks)\n    @name = name\n    @marks = marks\n  end\n\n  def average = marks.sum.to_f / marks.size\nend\n\nstudents = [Student.new("Ada", [90, 84, 77]), Student.new("Ben", [65, 72, 80])]\nstudents.sort_by { -_1.average }.each do |s|\n  puts "#{s.name}: #{s.average.round(1)}"\nend\n`,
      "README.md": readme("Ruby", ["▶ on `main.rb` runs it in a terminal; Run Task… has an irb REPL."]),
    },
  },
  {
    id: "typescript",
    label: "TypeScript (single file)",
    description: "TypeScript that runs in the JavaScript Console, no setup",
    icon: "symbol-namespace",
    language: "typescript",
    category: "Languages",
    files: {
      "main.ts": `type Shape = { kind: "circle"; r: number } | { kind: "rect"; w: number; h: number };\n\nfunction area(s: Shape): number {\n  switch (s.kind) {\n    case "circle":\n      return Math.PI * s.r ** 2;\n    case "rect":\n      return s.w * s.h;\n  }\n}\n\nconst shapes: Shape[] = [{ kind: "circle", r: 2 }, { kind: "rect", w: 3, h: 4 }];\nconsole.table(shapes.map((s) => ({ ...s, area: area(s).toFixed(2) })));\n`,
      "README.md": readme("TypeScript", ["▶ on `main.ts` runs it in the JavaScript Console (objects and tables shown, no install)."]),
    },
  },
  {
    id: "lua",
    label: "Lua",
    description: "A Lua script",
    icon: "symbol-method",
    language: "lua",
    category: "Languages",
    tools: ["lua"],
    files: {
      "main.lua": `local function fib(n)\n  if n < 2 then return n end\n  return fib(n - 1) + fib(n - 2)\nend\n\nfor i = 0, 10 do\n  io.write(fib(i), i < 10 and ", " or "\\n")\nend\n`,
      "README.md": readme("Lua", ["▶ on `main.lua` runs it in a terminal."]),
    },
  },
];
