import { gitignore, json, readme, type Template } from "./kit";

const page = (title: string, head: string, body: string, scripts = "") =>
  `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n    <title>${title}</title>\n${head}  </head>\n  <body>\n${body}${scripts}  </body>\n</html>\n`;

/** Static websites: live preview (F5), no build step. */
export const WEB: Template[] = [
  {
    id: "web",
    label: "Website (HTML, CSS, JavaScript)",
    description: "A page with live preview (F5)",
    icon: "globe",
    language: "html",
    category: "Websites",
    files: {
      "index.html": page("My site", `    <link rel="stylesheet" href="style.css" />\n`, `    <h1>Hello, web!</h1>\n    <button id="btn">Click me</button>\n`, `    <script src="script.js"></script>\n`),
      "style.css": `body {\n  font-family: system-ui, sans-serif;\n  max-width: 40rem;\n  margin: 4rem auto;\n}\n`,
      "script.js": `document.getElementById("btn").addEventListener("click", () => {\n  console.log("Clicked!");\n});\n`,
      "README.md": readme("Website", ["F5 on `index.html` opens the live preview. It reloads as you type."]),
    },
  },
  {
    id: "jquery",
    label: "Website with jQuery",
    description: "jQuery 3: DOM, events, animations and a JSON request",
    icon: "globe",
    language: "javascript",
    category: "Websites",
    files: {
      "index.html": page(
        "jQuery app",
        `    <link rel="stylesheet" href="style.css" />\n`,
        `    <main>\n      <h1>To-do list <small>with jQuery</small></h1>\n      <form id="add">\n        <input id="task" placeholder="Something to do" autocomplete="off" />\n        <button>Add</button>\n      </form>\n      <ul id="list"></ul>\n      <p id="count"></p>\n    </main>\n`,
        `    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>\n    <script src="app.js"></script>\n`,
      ),
      "app.js": `$(function () {\n  function update() {\n    const n = $("#list li").length;\n    $("#count").text(n + (n === 1 ? " task" : " tasks"));\n  }\n\n  $("#add").on("submit", function (e) {\n    e.preventDefault();\n    const text = $("#task").val().trim();\n    if (!text) return;\n    $("<li>")\n      .text(text)\n      .append($("<button>").addClass("remove").text("×"))\n      .hide()\n      .appendTo("#list")\n      .fadeIn(200);\n    $("#task").val("").focus();\n    update();\n  });\n\n  // Delegated event: works for items added later.\n  $("#list").on("click", ".remove", function () {\n    $(this).parent().fadeOut(200, function () {\n      $(this).remove();\n      update();\n    });\n  });\n\n  $("#list").on("click", "li", function () {\n    $(this).toggleClass("done");\n  });\n\n  update();\n  console.log("jQuery", $.fn.jquery, "is ready");\n});\n`,
      "style.css": `body {\n  font-family: system-ui, sans-serif;\n  background: #f4f6fb;\n}\nmain {\n  max-width: 28rem;\n  margin: 4rem auto;\n  padding: 1.5rem;\n  background: #fff;\n  border-radius: 12px;\n  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.08);\n}\nform {\n  display: flex;\n  gap: 0.5rem;\n}\ninput {\n  flex: 1;\n  padding: 0.5rem;\n}\nli {\n  display: flex;\n  justify-content: space-between;\n  padding: 0.4rem 0;\n  cursor: pointer;\n}\nli.done {\n  text-decoration: line-through;\n  color: #888;\n}\n.remove {\n  border: 0;\n  background: none;\n  color: #c00;\n  cursor: pointer;\n}\n`,
      "README.md": readme("jQuery website", ["F5 on `index.html` opens the live preview. jQuery loads from its CDN (internet needed).", "", "Open the JavaScript console in the preview to see `console.log` output."]),
    },
  },
  {
    id: "bootstrap",
    label: "Website with Bootstrap 5",
    description: "A responsive landing page: navbar, cards, grid and a modal",
    icon: "layout",
    language: "html",
    category: "Websites",
    files: {
      "index.html": page(
        "Bootstrap site",
        `    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />\n`,
        `    <nav class="navbar navbar-expand-lg bg-body-tertiary">\n      <div class="container">\n        <a class="navbar-brand" href="#">My School</a>\n        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav"><span class="navbar-toggler-icon"></span></button>\n        <div class="collapse navbar-collapse" id="nav">\n          <ul class="navbar-nav ms-auto">\n            <li class="nav-item"><a class="nav-link active" href="#">Home</a></li>\n            <li class="nav-item"><a class="nav-link" href="#courses">Courses</a></li>\n          </ul>\n        </div>\n      </div>\n    </nav>\n    <header class="container py-5 text-center">\n      <h1 class="display-5 fw-bold">Learn to build the web</h1>\n      <p class="lead">Bootstrap gives you a responsive grid and ready-made components.</p>\n      <button class="btn btn-primary btn-lg" data-bs-toggle="modal" data-bs-target="#join">Join now</button>\n    </header>\n    <section id="courses" class="container pb-5">\n      <div class="row g-4">\n        <div class="col-md-4"><div class="card h-100"><div class="card-body"><h5 class="card-title">HTML</h5><p class="card-text">Structure your pages.</p></div></div></div>\n        <div class="col-md-4"><div class="card h-100"><div class="card-body"><h5 class="card-title">CSS</h5><p class="card-text">Style and lay them out.</p></div></div></div>\n        <div class="col-md-4"><div class="card h-100"><div class="card-body"><h5 class="card-title">JavaScript</h5><p class="card-text">Make them interactive.</p></div></div></div>\n      </div>\n    </section>\n    <div class="modal fade" id="join" tabindex="-1">\n      <div class="modal-dialog"><div class="modal-content">\n        <div class="modal-header"><h5 class="modal-title">Join</h5><button class="btn-close" data-bs-dismiss="modal"></button></div>\n        <div class="modal-body"><input class="form-control" placeholder="Your email" /></div>\n        <div class="modal-footer"><button class="btn btn-primary" data-bs-dismiss="modal">Send</button></div>\n      </div></div>\n    </div>\n`,
        `    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>\n`,
      ),
      "README.md": readme("Bootstrap website", ["F5 on `index.html` opens the live preview. Resize the preview (device presets) to see the responsive grid."]),
    },
  },
  {
    id: "tailwind",
    label: "Website with Tailwind CSS",
    description: "Utility-first styling with the Tailwind Play CDN",
    icon: "symbol-color",
    language: "html",
    category: "Websites",
    files: {
      "index.html": page(
        "Tailwind site",
        `    <script src="https://cdn.tailwindcss.com"></script>\n`,
        `    <main class="min-h-screen bg-slate-50 flex items-center justify-center p-6">\n      <div class="max-w-md w-full bg-white rounded-2xl shadow-lg p-8 space-y-4">\n        <h1 class="text-2xl font-bold text-slate-800">Hello, Tailwind!</h1>\n        <p class="text-slate-600">Every class is one CSS rule: <code class="bg-slate-100 px-1 rounded">p-8</code> is padding, <code class="bg-slate-100 px-1 rounded">rounded-2xl</code> rounds corners.</p>\n        <button id="go" class="w-full rounded-lg bg-indigo-600 px-4 py-2 font-semibold text-white hover:bg-indigo-500 active:scale-95 transition">Click me</button>\n        <p id="out" class="text-center text-sm text-slate-500"></p>\n      </div>\n    </main>\n`,
        `    <script>\n      let n = 0;\n      document.getElementById("go").onclick = () => (document.getElementById("out").textContent = "Clicked " + ++n + " times");\n    </script>\n`,
      ),
      "README.md": readme("Tailwind website", ["F5 opens the live preview. The Play CDN builds the CSS in the browser (internet needed); use the Vite template with Tailwind for production."]),
    },
  },
  {
    id: "canvas-game",
    label: "JavaScript Game (Canvas)",
    description: "A canvas game loop with keyboard controls",
    icon: "game",
    language: "javascript",
    category: "Websites",
    files: {
      "index.html": page("Canvas game", `    <style>body{margin:0;display:grid;place-items:center;min-height:100vh;background:#111;color:#eee;font-family:system-ui}</style>\n`, `    <canvas id="game" width="480" height="320"></canvas>\n    <p>Arrow keys move the square. Catch the dots!</p>\n`, `    <script src="game.js"></script>\n`),
      "game.js": `const canvas = document.getElementById("game");\nconst ctx = canvas.getContext("2d");\nconst player = { x: 220, y: 140, size: 24, speed: 4 };\nlet dot = spawn();\nlet score = 0;\nconst keys = new Set();\naddEventListener("keydown", (e) => keys.add(e.key));\naddEventListener("keyup", (e) => keys.delete(e.key));\n\nfunction spawn() {\n  return { x: 20 + Math.random() * 440, y: 20 + Math.random() * 280 };\n}\n\nfunction update() {\n  if (keys.has("ArrowLeft")) player.x -= player.speed;\n  if (keys.has("ArrowRight")) player.x += player.speed;\n  if (keys.has("ArrowUp")) player.y -= player.speed;\n  if (keys.has("ArrowDown")) player.y += player.speed;\n  player.x = Math.max(0, Math.min(canvas.width - player.size, player.x));\n  player.y = Math.max(0, Math.min(canvas.height - player.size, player.y));\n  const cx = player.x + player.size / 2;\n  const cy = player.y + player.size / 2;\n  if (Math.hypot(cx - dot.x, cy - dot.y) < player.size / 2 + 6) {\n    score++;\n    dot = spawn();\n  }\n}\n\nfunction draw() {\n  ctx.fillStyle = "#1e1e2e";\n  ctx.fillRect(0, 0, canvas.width, canvas.height);\n  ctx.fillStyle = "#89b4fa";\n  ctx.fillRect(player.x, player.y, player.size, player.size);\n  ctx.fillStyle = "#f9e2af";\n  ctx.beginPath();\n  ctx.arc(dot.x, dot.y, 6, 0, Math.PI * 2);\n  ctx.fill();\n  ctx.fillStyle = "#cdd6f4";\n  ctx.font = "16px system-ui";\n  ctx.fillText("Score: " + score, 10, 22);\n}\n\nfunction loop() {\n  update();\n  draw();\n  requestAnimationFrame(loop);\n}\nloop();\n`,
      "README.md": readme("Canvas game", ["F5 on `index.html` opens the live preview. Click inside it, then use the arrow keys."]),
    },
  },
];

/** Frontend frameworks: npm install, then the dev server opens in the built-in browser. */
export const FRONTEND: Template[] = [
  {
    id: "react-vite",
    main: "src/App.tsx",
    label: "React (Vite + TypeScript)",
    description: "React 19 + Vite dev server, opens in the built-in browser",
    icon: "symbol-misc",
    language: "typescript",
    category: "Frontend frameworks",
    tools: ["node", "npm"],
    setup: { command: "npm install", note: "Installs React and Vite" },
    files: {
      "package.json": json({ name: "react-app", private: true, type: "module", scripts: { dev: "vite", build: "vite build", preview: "vite preview" }, dependencies: { react: "^19.0.0", "react-dom": "^19.0.0" }, devDependencies: { vite: "^7.0.0", "@vitejs/plugin-react": "^5.0.0", typescript: "^5.6.0", "@types/react": "^19.0.0", "@types/react-dom": "^19.0.0" } }),
      "index.html": `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>React App</title>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"></script>\n  </body>\n</html>\n`,
      "vite.config.ts": `import { defineConfig } from "vite";\nimport react from "@vitejs/plugin-react";\n\nexport default defineConfig({ plugins: [react()] });\n`,
      "tsconfig.json": json({ compilerOptions: { target: "ES2022", module: "ESNext", moduleResolution: "Bundler", jsx: "react-jsx", strict: true, skipLibCheck: true }, include: ["src"] }),
      "src/main.tsx": `import { StrictMode } from "react";\nimport { createRoot } from "react-dom/client";\nimport { App } from "./App";\nimport "./index.css";\n\ncreateRoot(document.getElementById("root")!).render(\n  <StrictMode>\n    <App />\n  </StrictMode>,\n);\n`,
      "src/App.tsx": `import { useState } from "react";\n\nexport function App() {\n  const [count, setCount] = useState(0);\n  return (\n    <main>\n      <h1>Hello from React</h1>\n      <button onClick={() => setCount((c) => c + 1)}>Clicked {count} times</button>\n    </main>\n  );\n}\n`,
      "src/index.css": `body {\n  font-family: system-ui, sans-serif;\n  margin: 0;\n  display: grid;\n  place-items: center;\n  min-height: 100vh;\n}\n`,
      ".gitignore": gitignore(),
      "README.md": readme("React app", ["Run Project (⌘/Ctrl+Shift+F10) starts `npm run dev` and opens the app in the built-in browser.", "", "Also works offline: F5 on `index.html` bundles it inside TMCode."]),
    },
  },
  {
    id: "react-js",
    main: "src/App.jsx",
    label: "React (Vite + JavaScript)",
    description: "React with plain JavaScript (JSX), no TypeScript",
    icon: "symbol-misc",
    language: "javascript",
    category: "Frontend frameworks",
    tools: ["node", "npm"],
    setup: { command: "npm install", note: "Installs React and Vite" },
    files: {
      "package.json": json({ name: "react-js-app", private: true, type: "module", scripts: { dev: "vite", build: "vite build", preview: "vite preview" }, dependencies: { react: "^19.0.0", "react-dom": "^19.0.0" }, devDependencies: { vite: "^7.0.0", "@vitejs/plugin-react": "^5.0.0" } }),
      "index.html": `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>React App</title>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.jsx"></script>\n  </body>\n</html>\n`,
      "vite.config.js": `import { defineConfig } from "vite";\nimport react from "@vitejs/plugin-react";\n\nexport default defineConfig({ plugins: [react()] });\n`,
      "src/main.jsx": `import { createRoot } from "react-dom/client";\nimport App from "./App.jsx";\n\ncreateRoot(document.getElementById("root")).render(<App />);\n`,
      "src/App.jsx": `import { useState } from "react";\n\nexport default function App() {\n  const [items, setItems] = useState(["Learn JSX"]);\n  const [text, setText] = useState("");\n  return (\n    <main style={{ fontFamily: "system-ui", maxWidth: 400, margin: "3rem auto" }}>\n      <h1>My list</h1>\n      <form onSubmit={(e) => { e.preventDefault(); if (text) setItems([...items, text]); setText(""); }}>\n        <input value={text} onChange={(e) => setText(e.target.value)} />\n        <button>Add</button>\n      </form>\n      <ul>{items.map((it, i) => <li key={i}>{it}</li>)}</ul>\n    </main>\n  );\n}\n`,
      ".gitignore": gitignore(),
      "README.md": readme("React (JavaScript)", ["Run Project starts `npm run dev` and opens the built-in browser."]),
    },
  },
  {
    id: "vue",
    main: "src/App.vue",
    label: "Vue 3 (Vite)",
    description: "Single-file components with the Composition API",
    icon: "symbol-misc",
    language: "javascript",
    category: "Frontend frameworks",
    tools: ["node", "npm"],
    setup: { command: "npm install", note: "Installs Vue and Vite" },
    files: {
      "package.json": json({ name: "vue-app", private: true, type: "module", scripts: { dev: "vite", build: "vite build", preview: "vite preview" }, dependencies: { vue: "^3.5.0" }, devDependencies: { vite: "^7.0.0", "@vitejs/plugin-vue": "^6.0.0" } }),
      "index.html": `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <title>Vue App</title>\n  </head>\n  <body>\n    <div id="app"></div>\n    <script type="module" src="/src/main.js"></script>\n  </body>\n</html>\n`,
      "vite.config.js": `import { defineConfig } from "vite";\nimport vue from "@vitejs/plugin-vue";\n\nexport default defineConfig({ plugins: [vue()] });\n`,
      "src/main.js": `import { createApp } from "vue";\nimport App from "./App.vue";\n\ncreateApp(App).mount("#app");\n`,
      "src/App.vue": `<script setup>\nimport { ref, computed } from "vue";\n\nconst items = ref([{ text: "Learn Vue", done: false }]);\nconst text = ref("");\nconst left = computed(() => items.value.filter((i) => !i.done).length);\n\nfunction add() {\n  if (!text.value) return;\n  items.value.push({ text: text.value, done: false });\n  text.value = "";\n}\n</script>\n\n<template>\n  <main>\n    <h1>Hello, Vue</h1>\n    <form @submit.prevent="add">\n      <input v-model="text" placeholder="New task" />\n      <button>Add</button>\n    </form>\n    <ul>\n      <li v-for="(item, i) in items" :key="i" :class="{ done: item.done }" @click="item.done = !item.done">{{ item.text }}</li>\n    </ul>\n    <p>{{ left }} left</p>\n  </main>\n</template>\n\n<style scoped>\nmain { font-family: system-ui; max-width: 400px; margin: 3rem auto; }\n.done { text-decoration: line-through; color: #888; }\nli { cursor: pointer; }\n</style>\n`,
      ".gitignore": gitignore(),
      "README.md": readme("Vue 3 app", ["Run Project starts `npm run dev` (Vite) and opens the built-in browser."]),
    },
  },
  {
    id: "svelte",
    main: "src/App.svelte",
    label: "Svelte 5 (Vite)",
    description: "Svelte components with runes",
    icon: "symbol-misc",
    language: "javascript",
    category: "Frontend frameworks",
    tools: ["node", "npm"],
    setup: { command: "npm install", note: "Installs Svelte and Vite" },
    files: {
      "package.json": json({ name: "svelte-app", private: true, type: "module", scripts: { dev: "vite", build: "vite build", preview: "vite preview" }, devDependencies: { svelte: "^5.0.0", vite: "^7.0.0", "@sveltejs/vite-plugin-svelte": "^6.0.0" } }),
      "index.html": `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <title>Svelte App</title>\n  </head>\n  <body>\n    <div id="app"></div>\n    <script type="module" src="/src/main.js"></script>\n  </body>\n</html>\n`,
      "vite.config.js": `import { defineConfig } from "vite";\nimport { svelte } from "@sveltejs/vite-plugin-svelte";\n\nexport default defineConfig({ plugins: [svelte()] });\n`,
      "src/main.js": `import { mount } from "svelte";\nimport App from "./App.svelte";\n\nmount(App, { target: document.getElementById("app") });\n`,
      "src/App.svelte": `<script>\n  let count = $state(0);\n  let doubled = $derived(count * 2);\n</script>\n\n<main>\n  <h1>Hello, Svelte</h1>\n  <button onclick={() => count++}>Clicked {count} times</button>\n  <p>Doubled: {doubled}</p>\n</main>\n\n<style>\n  main { font-family: system-ui; text-align: center; margin-top: 4rem; }\n</style>\n`,
      ".gitignore": gitignore(),
      "README.md": readme("Svelte app", ["Run Project starts `npm run dev` (Vite) and opens the built-in browser."]),
    },
  },
  {
    id: "angular",
    main: "src/app/app.component.ts",
    label: "Angular",
    description: "A standalone Angular app with signals, served by ng serve",
    icon: "symbol-misc",
    language: "typescript",
    category: "Frontend frameworks",
    tools: ["node", "npm"],
    setup: { command: "npm install", note: "Installs Angular (a few minutes the first time)" },
    files: {
      "package.json": json({
        name: "angular-app",
        private: true,
        scripts: { start: "ng serve", build: "ng build", ng: "ng" },
        dependencies: { "@angular/common": "^19.2.0", "@angular/compiler": "^19.2.0", "@angular/core": "^19.2.0", "@angular/forms": "^19.2.0", "@angular/platform-browser": "^19.2.0", rxjs: "~7.8.0", tslib: "^2.6.0", "zone.js": "~0.15.0" },
        devDependencies: { "@angular/build": "^19.2.0", "@angular/cli": "^19.2.0", "@angular/compiler-cli": "^19.2.0", typescript: "~5.7.0" },
      }),
      "angular.json": json({
        $schema: "./node_modules/@angular/cli/lib/config/schema.json",
        version: 1,
        newProjectRoot: "projects",
        cli: { analytics: false },
        projects: {
          app: {
            projectType: "application",
            root: "",
            sourceRoot: "src",
            prefix: "app",
            architect: {
              build: { builder: "@angular/build:application", options: { outputPath: "dist/app", index: "src/index.html", browser: "src/main.ts", polyfills: ["zone.js"], tsConfig: "tsconfig.json", styles: ["src/styles.css"] }, configurations: { development: { optimization: false, extractLicenses: false, sourceMap: true } }, defaultConfiguration: "development" },
              serve: { builder: "@angular/build:dev-server", configurations: { development: { buildTarget: "app:build:development" } }, defaultConfiguration: "development" },
            },
          },
        },
      }),
      "tsconfig.json": json({ compilerOptions: { target: "ES2022", module: "ES2022", moduleResolution: "bundler", strict: true, experimentalDecorators: true, skipLibCheck: true, lib: ["ES2022", "dom"] }, files: ["src/main.ts"], angularCompilerOptions: { strictTemplates: true } }),
      "src/index.html": `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8" />\n    <title>Angular App</title>\n    <base href="/" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n  </head>\n  <body>\n    <app-root></app-root>\n  </body>\n</html>\n`,
      "src/main.ts": `import { bootstrapApplication } from "@angular/platform-browser";\nimport { AppComponent } from "./app/app.component";\n\nbootstrapApplication(AppComponent).catch((err) => console.error(err));\n`,
      "src/app/app.component.ts": `import { Component, computed, signal } from "@angular/core";\nimport { FormsModule } from "@angular/forms";\n\n@Component({\n  selector: "app-root",\n  standalone: true,\n  imports: [FormsModule],\n  template: \`\n    <main>\n      <h1>Hello, Angular</h1>\n      <form (ngSubmit)="add()">\n        <input [(ngModel)]="text" name="text" placeholder="New task" />\n        <button>Add</button>\n      </form>\n      <ul>\n        @for (task of tasks(); track $index) {\n          <li>{{ task }}</li>\n        }\n      </ul>\n      <p>{{ count() }} tasks</p>\n    </main>\n  \`,\n})\nexport class AppComponent {\n  text = "";\n  tasks = signal<string[]>(["Learn Angular"]);\n  count = computed(() => this.tasks().length);\n\n  add() {\n    if (!this.text.trim()) return;\n    this.tasks.update((t) => [...t, this.text.trim()]);\n    this.text = "";\n  }\n}\n`,
      "src/styles.css": `body {\n  font-family: system-ui, sans-serif;\n  max-width: 30rem;\n  margin: 3rem auto;\n}\n`,
      ".gitignore": gitignore([".angular/"]),
      "README.md": readme("Angular app", ["Run Project starts `ng serve` (port 4200) and opens the built-in browser.", "", "Generate parts with the Angular CLI in the terminal: `npx ng generate component todo`."]),
    },
  },
  {
    id: "nextjs",
    main: "app/page.tsx",
    label: "Next.js (App Router)",
    description: "React pages and an API route in one project",
    icon: "symbol-misc",
    language: "typescript",
    category: "Frontend frameworks",
    tools: ["node", "npm"],
    setup: { command: "npm install", note: "Installs Next.js" },
    files: {
      "package.json": json({ name: "next-app", private: true, scripts: { dev: "next dev", build: "next build", start: "next start" }, dependencies: { next: "^15.0.0", react: "^19.0.0", "react-dom": "^19.0.0" }, devDependencies: { typescript: "^5.6.0", "@types/react": "^19.0.0", "@types/node": "^22.0.0" } }),
      "tsconfig.json": json({ compilerOptions: { target: "ES2022", lib: ["dom", "dom.iterable", "esnext"], strict: true, module: "esnext", moduleResolution: "bundler", jsx: "preserve", noEmit: true, incremental: true, skipLibCheck: true, allowJs: true, esModuleInterop: true, isolatedModules: true, resolveJsonModule: true, plugins: [{ name: "next" }] }, include: ["**/*.ts", "**/*.tsx", "next-env.d.ts"], exclude: ["node_modules"] }),
      "app/layout.tsx": `export const metadata = { title: "Next.js app" };\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body style={{ fontFamily: "system-ui", maxWidth: 640, margin: "3rem auto" }}>{children}</body>\n    </html>\n  );\n}\n`,
      "app/page.tsx": `export default async function Home() {\n  return (\n    <main>\n      <h1>Hello, Next.js</h1>\n      <p>This page renders on the server. The API route answers at <a href="/api/hello">/api/hello</a>.</p>\n    </main>\n  );\n}\n`,
      "app/api/hello/route.ts": `export function GET() {\n  return Response.json({ message: "Hello from a Next.js route", time: new Date().toISOString() });\n}\n`,
      ".gitignore": gitignore([".next/", "next-env.d.ts"]),
      "README.md": readme("Next.js app", ["Run Project starts `next dev` (port 3000) and opens the built-in browser.", "", "Test the API route with Run › Open API Tester."]),
    },
  },
];
